name: Sync all branches

on:
  # watch:
  #   types: started
  schedule:
    - cron: 0 */2 * * *

jobs:
  update_lede_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          upstream_repository: coolsnowwolf/lede
          target_repository: hyy-666/lede
          upstream_branch: master
          target_branch: my-diy
          force: false
          tags: false
